#!/bin/bash
arg=$1

if [[ "$arg" -eq 1 ]]
then
	sudo service nginx start;
	sudo systemctl start adposter;
	sudo systemctl enable adposter;
	echo "[run] - adposter запущен"
elif [[ "$arg" -eq 2 ]]
then
	sudo systemctl restart adposter;
	sudo systemctl restart nginx;
	echo "[restart] - adposter перезапущен"
elif [[ "$arg" -eq 3 ]
then
	sudo systemctl status nginx;
	sudo systemctl status adposter;
	echo "[status] - adposter статус"
else
	sudo systemctl stop adposter;
	sudo systemctl stop nginx;
	echo "[stop] - adposter выключен"
fi

exit 0
